### ISSUE TITLE
ASAN03 - Profile Data Session Issue

### ISSUE THREAD

**Issue by reiuu23** [reiuu23/asan#7]
Fix core session update on application root and add session reset when refetching new data across all the application render.

**Comment by reiuu23** [comment]
- Profile data session updates when a user updates their profile data but when the user refreshes the session data of the core features of the app, the profile gets left behind. Profile session contains the verification status of the user so as much as possible, implement session refetch alongside the onRefresh section of the home page.

**Comment by reimnjoo** [comment]
Done, as per the release of the official version 1.
